language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_25e713513946_key -iv $encrypted_25e713513946_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod +x mvnw
- mv src/main/resources/application-dev.yml src/main/resources/application.yml
- cat src/main/resources/application.yml
- sed -i "9 s/root/$PASSWD/" src/main/resources/application.yml
- sed -i "s/127.0.0.1/$DBIP/g" src/main/resources/application.yml
addons:
  ssh_known_hosts: "$IP"
branches:
  only:
  - master
install:
- sh mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
script:
after_script:
- pwd
- scp -o StrictHostKeyChecking=no -r target/  root@$IP:/opt/zz/
- ssh root@$IP 'cd /opt/zz/ && sh /opt/zz/travisAuto.sh start'
